'use strict';
const key='mohid-campus-v1';
const initial=[{id:'ST-1001',name:'Aarav Sharma',department:'Computer Science',attended:48,classes:50,fees:'Paid'},{id:'ST-1002',name:'Sara Ahmed',department:'Computer Science',attended:45,classes:50,fees:'Pending'},{id:'ST-1003',name:'Rohan Reddy',department:'Electronics',attended:44,classes:50,fees:'Paid'},{id:'ST-1004',name:'Meera Rao',department:'Mechanical',attended:47,classes:50,fees:'Paid'},{id:'ST-1005',name:'Kabir Patel',department:'Electronics',attended:42,classes:50,fees:'Pending'},{id:'ST-1006',name:'Ananya Das',department:'Mechanical',attended:49,classes:50,fees:'Paid'}];
let students=structuredClone(initial),editing=null,storageAvailable=true;
try{const saved=JSON.parse(localStorage.getItem(key));if(Array.isArray(saved)&&saved.every(s=>typeof s.id==='string'&&typeof s.name==='string'&&['Computer Science','Electronics','Mechanical'].includes(s.department)&&Number.isInteger(s.classes)&&s.classes>=0&&Number.isInteger(s.attended)&&s.attended>=0&&s.attended<=s.classes&&['Paid','Pending'].includes(s.fees)))students=saved;}catch{storageAvailable=false;}
const $=s=>document.querySelector(s),escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function announce(message){$('#status').textContent=message;}
function persist(message){try{localStorage.setItem(key,JSON.stringify(students));announce(message+' Saved in this browser.');}catch{announce(message+' Browser storage unavailable: changes will be lost on refresh.');}}
function filtered(){const q=$('#search').value.toLowerCase().trim(),dept=$('#filter').value;return students.filter(s=>(s.name+' '+s.id).toLowerCase().includes(q)&&(dept==='all'||s.department===dept));}
function render(){const list=filtered();$('#total').textContent=students.length;const attended=students.reduce((a,s)=>a+s.attended,0),classes=students.reduce((a,s)=>a+s.classes,0);$('#average').textContent=classes?Math.round(attended/classes*100)+'%':'—';$('#pending').textContent=students.filter(s=>s.fees==='Pending').length;$('#departments').textContent=new Set(students.map(s=>s.department)).size;$('#rows').innerHTML=list.length?list.map(s=>`<tr><td><small>${escapeHTML(s.id)}</small><br>${escapeHTML(s.name)}</td><td>${escapeHTML(s.department)}</td><td>${s.classes?Math.round(s.attended/s.classes*100)+'%':'—'} <small>(${s.attended}/${s.classes})</small></td><td>${s.fees}</td><td class="row-actions"><button class="small-button" data-action="present" data-id="${escapeHTML(s.id)}" aria-label="Mark ${escapeHTML(s.name)} present">Present</button><button class="small-button" data-action="absent" data-id="${escapeHTML(s.id)}" aria-label="Mark ${escapeHTML(s.name)} absent">Absent</button><button class="small-button" data-action="edit" data-id="${escapeHTML(s.id)}" aria-label="Edit ${escapeHTML(s.name)}">Edit</button><button class="small-button danger" data-action="delete" data-id="${escapeHTML(s.id)}" aria-label="Delete ${escapeHTML(s.name)}">Delete</button></td></tr>`).join(''):'<tr><td colspan="5">No students found. Add a student or change your filters.</td></tr>';}
function openEditor(student){editing=student?.id||null;$('#editor').hidden=false;$('#editor-title').textContent=student?'Edit student':'Add a student';$('#student-form').reset();if(student)for(const name of ['name','department','attended','classes','fees'])$('#student-form').elements[name].value=student[name];$('#student-form').elements.name.focus();$('#editor').scrollIntoView({block:'center',behavior:'smooth'});}
$('#add-student').addEventListener('click',()=>openEditor());$('#cancel-edit').addEventListener('click',()=>{$('#editor').hidden=true;editing=null;$('#add-student').focus();});
$('#student-form').addEventListener('submit',e=>{e.preventDefault();const f=e.target;const attended=Number(f.elements.attended.value),classes=Number(f.elements.classes.value),name=f.elements.name.value.trim();if(!name){announce('Please enter a name.');return;}if(attended>classes){announce('Attended classes cannot exceed total classes.');f.elements.attended.focus();return;}const record={id:editing||'ST-'+Date.now().toString(36).toUpperCase(),name,department:f.elements.department.value,attended,classes,fees:f.elements.fees.value};if(editing)students=students.map(s=>s.id===editing?record:s);else students.push(record);persist(editing?'Student updated.':'Student added.');editing=null;$('#editor').hidden=true;render();$('#add-student').focus();});
$('#rows').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const student=students.find(s=>s.id===b.dataset.id);if(!student)return;switch(b.dataset.action){case'edit':openEditor(student);return;case'delete':if(!confirm(`Delete ${student.name}? This removes this browser's record.`))return;students=students.filter(s=>s.id!==student.id);if(editing===student.id){editing=null;$('#editor').hidden=true;}persist('Student deleted.');break;default:student.classes++;if(b.dataset.action==='present')student.attended++;persist(`${student.name} marked ${b.dataset.action}.`);}render();});
$('#search').addEventListener('input',render);$('#filter').addEventListener('change',render);
$('#export').addEventListener('click',()=>{const cell=v=>'"'+String(v).replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';const rows=[['Student ID','Name','Department','Attended','Total classes','Fee status'],...filtered().map(s=>[s.id,s.name,s.department,s.attended,s.classes,s.fees])];const blob=new Blob(['\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='campus-students.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);announce('Exported '+filtered().length+' student records.');});
$('#reset').addEventListener('click',()=>{if(!confirm('Replace all current records with the six original fictional students?'))return;students=structuredClone(initial);editing=null;$('#editor').hidden=true;$('#search').value='';$('#filter').value='all';persist('Sample records restored.');render();});render();if(!storageAvailable)announce('Browser storage unavailable. You can use the app, but changes may not persist.');
