'use strict';
const $=s=>document.querySelector(s);let seed=42;const rand=()=>{seed=(Math.imul(1664525,seed)+1013904223)>>>0;return seed/4294967296;};
const samples=Array.from({length:1000},()=>{const x=rand(),y=rand(),noise=(rand()-.5)*.26;return {x,y,label:x*.68+y*.82+noise>1.02?1:0};});
const training=samples.slice(0,800),test=samples.slice(800);let weights=null,trainingNow=false;
const sigmoid=z=>1/(1+Math.exp(-Math.max(-40,Math.min(40,z))));
const predict=(s,w)=>sigmoid(w[0]+w[1]*(s.x-.5)*2+w[2]*(s.y-.5)*2);
const canvas=$('#plot'),ctx=canvas.getContext('2d');
function draw(){const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);canvas.width=r.width*dpr;canvas.height=r.height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);const w=r.width,h=r.height,pad=20;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#3b482f';for(let i=0;i<=4;i++){const x=pad+(w-2*pad)*i/4,y=pad+(h-2*pad)*i/4;ctx.beginPath();ctx.moveTo(x,pad);ctx.lineTo(x,h-pad);ctx.moveTo(pad,y);ctx.lineTo(w-pad,y);ctx.stroke();}if(weights){for(let x=0;x<1;x+=.04)for(let y=0;y<1;y+=.04){ctx.fillStyle=predict({x,y},weights)>.5?'#ff6b351a':'#afcd8520';ctx.fillRect(pad+x*(w-2*pad),h-pad-(y+.04)*(h-2*pad),.04*(w-2*pad),.04*(h-2*pad));}}for(const s of test){ctx.fillStyle=s.label?'#ff8550':'#b5d59a';ctx.beginPath();ctx.arc(pad+s.x*(w-2*pad),h-pad-s.y*(h-2*pad),2.5,0,Math.PI*2);ctx.fill();}}
new ResizeObserver(draw).observe(canvas);
$('#train').addEventListener('click',async()=>{if(trainingNow)return;trainingNow=true;weights=null;$('#train').disabled=true;$('#balance').disabled=true;$('#predict').disabled=true;$('#download').disabled=true;$('#prediction').hidden=true;$('#accuracy').textContent=$('#recall').textContent='—';let w=[0,0,0];const positives=training.filter(s=>s.label).length,balanced=$('#balance').checked;const positiveWeight=balanced?training.length/(2*positives):1,negativeWeight=balanced?training.length/(2*(training.length-positives)):1;for(let epoch=0;epoch<350;epoch++){const gradient=[0,0,0];for(const s of training){const error=(predict(s,w)-s.label)*(s.label?positiveWeight:negativeWeight);gradient[0]+=error;gradient[1]+=error*(s.x-.5)*2;gradient[2]+=error*(s.y-.5)*2;}w=w.map((value,i)=>value-.35*gradient[i]/training.length);if(epoch%10===0){$('#progress').value=epoch;$('#training-status').textContent=`Training epoch ${epoch+1} / 350…`;await new Promise(resolve=>requestAnimationFrame(resolve));}}weights=w;let tp=0,tn=0,fp=0,fn=0;for(const s of test){const result=predict(s,w)>=.5;if(result&&s.label)tp++;else if(result)fp++;else if(s.label)fn++;else tn++;}$('#accuracy').textContent=((tp+tn)/test.length*100).toFixed(1)+'%';$('#recall').textContent=(tp+fn?tp/(tp+fn)*100:0).toFixed(1)+'%';for(const [id,value]of Object.entries({tp,tn,fp,fn}))$('#'+id).textContent=value;$('#progress').value=350;$('#training-status').textContent=`Training complete · 350 epochs · class balancing ${balanced?'on':'off'}.`;$('#train').disabled=false;$('#train').textContent='Retrain model ↗';$('#balance').disabled=false;$('#predict').disabled=false;$('#predict').textContent='Run prediction ↗';$('#download').disabled=false;trainingNow=false;draw();});
for(const id of ['temperature','vibration'])$('#'+id).addEventListener('input',e=>{$('#'+id+'-value').textContent=Number(e.target.value).toFixed(2);$('#prediction').hidden=true;});
$('#predict-form').addEventListener('submit',e=>{e.preventDefault();if(!weights)return;const input={x:Number($('#temperature').value),y:Number($('#vibration').value)},score=predict(input,weights),label=score>=.5?'Inspection suggested':'Normal pattern';$('#result-label').textContent=label;$('#probability').textContent=`Inspection-class score: ${(score*100).toFixed(1)}%. Educational output from synthetic data; not operational advice.`;$('#json-result').textContent=JSON.stringify({model:'logistic-regression',synthetic_data:true,input:{temperature:input.x,vibration:input.y},inspection_score:Number(score.toFixed(4)),threshold:0.5,prediction:score>=.5?1:0},null,2);$('#prediction').hidden=false;});
$('#download').addEventListener('click',()=>{if(!weights)return;const payload={model:'logistic-regression',weights,feature_transform:'(value - 0.5) * 2',features:['temperature','vibration'],threshold:0.5,synthetic_data:true,seed:42,epochs:350};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='inference-lab-model.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
